# -*- coding: utf-8 -*-
"""frames.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HbiBcmKCNCso1QpFeiXUF3jGnJt3H6iN
"""

import cv2

from google.colab import drive
drive.mount('/content/drive')

cam = cv2.VideoCapture("/content/drive/My Drive/BITSAuto/Assignment_2/Videos/horizontal.mp4")
fps = cam.get(cv2.CAP_PROP_FPS)
print(fps)

n = 0
i = 0
while True:
  ret, frame = cam.read()
  if not ret:
      break


  if (n)%(20) == 0:
      cv2.imwrite("/content/drive/My Drive/BITSAuto/Assignment_2/Videos/Horizontal_frames/{}.jpg".format(i), frame)
      i += 1
      print(i)

  n += 1

cam.release()
cv2.destroyAllWindows()